version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
      target-branch: 'chore/dependabot'
      labels: ['dependabot']
      open-pull-requests-limit: 10
      commit-message:
          prefix: "chore"
      ignore:
          - dependency-name: 'rollup'
          - dependency-name: 'browserify'
          - dependency-name: '@babel/runtime'
