name: Reusable Workflows

on:
  pull_request:

jobs:
  pr-branch-check-name:
    name: Check PR for semantic branch name
    uses: mParticle/mparticle-workflows/.github/workflows/pr-branch-check-name.yml@stable
  pr-title-check:
    name: Check PR for semantic title
    uses: mParticle/mparticle-workflows/.github/workflows/pr-title-check.yml@stable
  pr-branch-target-gitflow:
    name: Check PR for semantic target branch
    uses: mParticle/mparticle-workflows/.github/workflows/pr-branch-target-gitflow.yml@stable
  security-lint-checks:
    name: Security Lint Checks
    uses: mparticle/mparticle-workflows/.github/workflows/security-checks.yml@main
    with:
      base_branch: "development"